<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">

  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <RootNamespace>AutoPalExplorer</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>x64</PlatformTarget>

    <!-- 插件版本。build.sh 会自动递增最后一位并同步到 ../Pal/Pal.json。
         也可用 IDE 直接构建，此时使用下面这个固定值（不会自增）。 -->
    <Version>1.0.0.32</Version>

    <!-- 输出目录直接是 bin/Release/AutoPalExplorer.dll，方便 Dalamud & Packager -->
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>

    <IsPackable>true</IsPackable>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="ECommons" Version="3.2.1.15" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.4" />
    <PackageReference Include="SQLitePCLRaw.core" Version="2.1.4" />
  </ItemGroup>

  <ItemGroup>
    <!-- 确保插件 json 跟着 DLL 一起到输出目录 -->
    <None Update="AutoPalExplorer.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\logo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </Content>
  </ItemGroup>
</Project>
